### ISSUE TITLE
index.js:1 Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by starstatus** [nemophrost/react-onclickoutside#1]
What's this error about?

**Comment by starstatus** [comment]
BTW, I have the latest babel installed in the project.

**Comment by nemophrost** [comment]
You need to make sure whatever you are using to have Babel compile your code is including the plugin.

If you are using webpack, you need to add the plugin as one of your includes for your js loader.

For example:

``` javascript
{
  test: /\.(js|jsx)$/,
  loader: 'babel',
  include: [
    path.join(__dirname, './node_modules', 'react-onclickoutside-es6'), // something like this
    path.join(__dirname, './src'),
    ...
  ]
}
```
